# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'liberate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liberate
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'
  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/DynamicLinks', '~> 5.15.0'
  pod 'RNGestureHandler',
    :path => '../node_modules/react-native-gesture-handler'
  pod 'React',
    :path => "../node_modules/react-native",
    :inhibit_warnings => true,
    :subspecs => [
      "Core",
      "ART",
      "RCTActionSheet",
      "RCTAnimation",
      "RCTCameraRoll",
      "RCTGeolocation",
      "RCTImage",
      "RCTNetwork",
      "RCTText",
      "RCTVibration",
      "RCTWebSocket",
      "DevSupport",
      "CxxBridge"
    ]
    pod 'yoga',
      :path => "../node_modules/react-native/ReactCommon/yoga",
      :inhibit_warnings => true
    pod 'Folly',
      :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec",
      :inhibit_warnings => true

      post_install do |installer|
        installer.pods_project.targets.each do |target|

          # The following is needed to ensure the "archive" step works in XCode.
          # It removes React & Yoga from the Pods project, as it is already included in the main project.
          # Without this, you'd see errors when you archive like:
          # "Multiple commands produce ... libReact.a"
          # "Multiple commands produce ... libyoga.a"

          targets_to_ignore = %w(React yoga)

          if targets_to_ignore.include? target.name
            target.remove_from_project
          end

        end
      end

  target 'liberateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'liberate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for liberate-tvOS

  target 'liberate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
